uses
  m_pathes_windows,
  m_moduleconfig_ini,
  m_log_file,
  m_language_textfile,
  m_glcontext_sdl,
  m_inputhandler_sdl,
  m_glmng_default,
  m_texmng_default,
  m_shdmng_default,
  m_font_texture,
  m_gui_default,
  m_gui_window_default,
  m_gui_label_default,
  m_gui_progressbar_default,
  m_gui_button_default,
  m_gui_iconifiedbutton_default,
  m_gui_edit_default,
  m_gui_timer_default,
  m_loadscreen_default,
  m_mainmenu_screenshots,
  m_ocfmng_default,
  m_renderer_opengl,
  m_camera_default,
  SysUtils,
  Classes;
type
  TModulePathes = TModulePathesWindows;
  TModuleConfig = TModuleConfigIni;
  TModuleLog = TModuleLogFile;
  TModuleLanguage = TModuleLanguageTextFile;
  TModuleGLContext = TModuleGLContextSDL;
  TModuleInputHandler = TModuleInputHandlerSDL;
  TModuleGLMng = TModuleGLMngDefault;
  TModuleTextureManager = TModuleTextureManagerDefault;
  TModuleShaderManager = TModuleShaderManagerDefault;
  TModuleFont = TModuleFontTexture;
  TModuleGUI = TModuleGUIDefault;
  TModuleGUIWindow = TModuleGUIWindowDefault;
  TModuleGUILabel = TModuleGUILabelDefault;
  TModuleGUIProgressBar = TModuleGUIProgressBarDefault;
  TModuleGUIButton = TModuleGUIButtonDefault;
  TModuleGUIIconifiedButton = TModuleGUIIconifiedButtonDefault;
  TModuleGUIEdit = TModuleGUIEditDefault;
  TModuleGUITimer = TModuleGUITimerDefault;
  TModuleLoadScreen = TModuleLoadScreenDefault;
  TModuleMainMenu = TModuleMainMenuScreenshots;
  TModuleOCFManager = TModuleOCFManagerDefault;
  TModuleRenderer = TModuleRendererOpenGL;
  TModuleCamera = TModuleCameraDefault;
