uses
  m_pathes_windows,
  m_moduleconfig_xml,
  m_log_file,
  m_language_textfile,
  m_glcontext_sdl,
  m_inputhandler_sdl,
  m_glmng_default,
  m_texmng_default,
  m_shdmng_dynamic,
  m_font_textureVariableWidth,
  m_gui_default,
  m_gui_window_default,
  m_gui_tabbar_default,
  m_gui_scrollbox_default,
  m_gui_label_default,
  m_gui_image_default,
  m_gui_progressbar_default,
  m_gui_button_default,
  m_gui_checkbox_default,
  m_gui_iconifiedbutton_default,
  m_gui_edit_default,
  m_gui_slider_default,
  m_gui_timer_default,
  m_loadscreen_default,
  m_mainmenu_modern,
  m_ocfmng_default,
  m_renderer_owe,
  m_camera_default,
  m_settings_default,
  m_scriptmng_bytecode,
  m_sound_openal,
  m_backgroundmusic_default,
  SysUtils,
  Classes;
type
  TModulePathes = TModulePathesWindows;
  TModuleConfig = TModuleConfigXml;
  TModuleLog = TModuleLogFile;
  TModuleLanguage = TModuleLanguageTextFile;
  TModuleGLContext = TModuleGLContextSDL;
  TModuleInputHandler = TModuleInputHandlerSDL;
  TModuleGLMng = TModuleGLMngDefault;
  TModuleTextureManager = TModuleTextureManagerDefault;
  TModuleShaderManager = TModuleShaderManagerDynamic;
  TModuleFont = TModuleFontTextureVariableWidth;
  TModuleGUI = TModuleGUIDefault;
  TModuleGUIWindow = TModuleGUIWindowDefault;
  TModuleGUITabBar = TModuleGUITabBarDefault;
  TModuleGUIScrollBox = TModuleGUIScrollBoxDefault;
  TModuleGUILabel = TModuleGUILabelDefault;
  TModuleGUIImage = TModuleGUIImageDefault;
  TModuleGUIProgressBar = TModuleGUIProgressBarDefault;
  TModuleGUIButton = TModuleGUIButtonDefault;
  TModuleGUICheckBox = TModuleGUICheckBoxDefault;
  TModuleGUIIconifiedButton = TModuleGUIIconifiedButtonDefault;
  TModuleGUIEdit = TModuleGUIEditDefault;
  TModuleGUISlider = TModuleGUISliderDefault;
  TModuleGUITimer = TModuleGUITimerDefault;
  TModuleLoadScreen = TModuleLoadScreenDefault;
  TModuleMainMenu = TModuleMainMenuModern;
  TModuleOCFManager = TModuleOCFManagerDefault;
  TModuleRenderer = TModuleRendererOWE;
  TModuleCamera = TModuleCameraDefault;
  TModuleSettings = TModuleSettingsDefault;
  TModuleScriptManager = TModuleScriptManagerBytecode;
  TModuleSound = TModuleSoundOpenAL;
  TModuleBackgroundMusic = TModuleBackgroundMusicDefault;
